apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kinugasa-recording

resources:
- namespace.yaml
- ../../base/livekit

configMapGenerator:
- name: livekit-runtime-env
  behavior: merge
  literals:
  - NODE_IP=172.18.0.2
  - LIVEKIT_RTC_TCP_PORT=31877

generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: Deployment
    name: livekit
  path: livekit-rtc-container-port-patch.yaml
- path: livekit-nodeport-service-patch.yaml
