apiVersion: v1
kind: Service
metadata:
  name: livekit
spec:
  type: NodePort
  ports:
  - name: signal
    port: 7880
    targetPort: signal
    nodePort: 30780
    protocol: TCP
  - name: rtc-tcp
    port: 7881
    targetPort: rtc-tcp
    nodePort: 31877
    protocol: TCP
