apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kinugasa-recording-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kinugasa-recording-operator
subjects:
  - kind: ServiceAccount
    name: kinugasa-recording-operator
    namespace: kinugasa-recording
