apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kinugasa-recording
resources:
  - ../../../default
  - garage.yaml

patches:
  - path: s3-config-patch.yaml
  - path: s3-secret-patch.yaml
