//go:build !ignore_autogenerated

// Copyright 2026 The kinugasa-recording Authors.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CameraEndpoints) DeepCopyInto(out *CameraEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CameraEndpoints.
func (in *CameraEndpoints) DeepCopy() *CameraEndpoints {
	if in == nil {
		return nil
	}
	out := new(CameraEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CameraIngressSpec) DeepCopyInto(out *CameraIngressSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CameraIngressSpec.
func (in *CameraIngressSpec) DeepCopy() *CameraIngressSpec {
	if in == nil {
		return nil
	}
	out := new(CameraIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CameraSpec) DeepCopyInto(out *CameraSpec) {
	*out = *in
	out.Ingress = in.Ingress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CameraSpec.
func (in *CameraSpec) DeepCopy() *CameraSpec {
	if in == nil {
		return nil
	}
	out := new(CameraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CameraStatus) DeepCopyInto(out *CameraStatus) {
	*out = *in
	if in.LastFrameAt != nil {
		in, out := &in.LastFrameAt, &out.LastFrameAt
		*out = (*in).DeepCopy()
	}
	out.Endpoints = in.Endpoints
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CameraStatus.
func (in *CameraStatus) DeepCopy() *CameraStatus {
	if in == nil {
		return nil
	}
	out := new(CameraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Session) DeepCopyInto(out *Session) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Session.
func (in *Session) DeepCopy() *Session {
	if in == nil {
		return nil
	}
	out := new(Session)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Session) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionList) DeepCopyInto(out *SessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Session, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionList.
func (in *SessionList) DeepCopy() *SessionList {
	if in == nil {
		return nil
	}
	out := new(SessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionSpec) DeepCopyInto(out *SessionSpec) {
	*out = *in
	if in.ReservedCameraNames != nil {
		in, out := &in.ReservedCameraNames, &out.ReservedCameraNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedTakeNames != nil {
		in, out := &in.ReservedTakeNames, &out.ReservedTakeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cameras != nil {
		in, out := &in.Cameras, &out.Cameras
		*out = make([]CameraSpec, len(*in))
		copy(*out, *in)
	}
	if in.Takes != nil {
		in, out := &in.Takes, &out.Takes
		*out = make([]TakeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionSpec.
func (in *SessionSpec) DeepCopy() *SessionSpec {
	if in == nil {
		return nil
	}
	out := new(SessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionStatus) DeepCopyInto(out *SessionStatus) {
	*out = *in
	if in.Cameras != nil {
		in, out := &in.Cameras, &out.Cameras
		*out = make([]CameraStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Takes != nil {
		in, out := &in.Takes, &out.Takes
		*out = make([]TakeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionStatus.
func (in *SessionStatus) DeepCopy() *SessionStatus {
	if in == nil {
		return nil
	}
	out := new(SessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TakeCameraStatus) DeepCopyInto(out *TakeCameraStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TakeCameraStatus.
func (in *TakeCameraStatus) DeepCopy() *TakeCameraStatus {
	if in == nil {
		return nil
	}
	out := new(TakeCameraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TakeSpec) DeepCopyInto(out *TakeSpec) {
	*out = *in
	if in.CameraNames != nil {
		in, out := &in.CameraNames, &out.CameraNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	if in.StopRequestedAt != nil {
		in, out := &in.StopRequestedAt, &out.StopRequestedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TakeSpec.
func (in *TakeSpec) DeepCopy() *TakeSpec {
	if in == nil {
		return nil
	}
	out := new(TakeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TakeStatus) DeepCopyInto(out *TakeStatus) {
	*out = *in
	if in.Cameras != nil {
		in, out := &in.Cameras, &out.Cameras
		*out = make([]TakeCameraStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TakeStatus.
func (in *TakeStatus) DeepCopy() *TakeStatus {
	if in == nil {
		return nil
	}
	out := new(TakeStatus)
	in.DeepCopyInto(out)
	return out
}
