[package]
name = "kinugasa-mysql"
description = "MySQL repository adapter for kinugasa recording v3"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
kinugasa-core = { path = "../kinugasa-core" }
sqlx = { workspace = true, features = [
    "runtime-tokio-rustls",
    "mysql",
    "chrono",
    "uuid",
    "migrate",
    "macros",
] }
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
